import { describe, it, expect, vi } from 'vitest';

vi.mock('wxt/modules', () => ({
  defineWxtModule: vi.fn((config) => config),
  addEntrypoint: vi.fn(),
}));

import moduleExport from '../src/index';
import type { ExtPayConfig } from '../src/pro-status';

/** Run setup and the prepare:types hook; return the generated file's text. */
async function generate(options: Record<string, unknown>): Promise<string> {
  let hook: ((_: unknown, entries: Array<{ path: string; text: string }>) => void) | undefined;
  const wxt = {
    config: { outDir: '/out', wxtDir: '/wxt' },
    hooks: { hook: (_event: string, cb: typeof hook) => { hook = cb; } },
  };
  await (moduleExport as any).setup(wxt, options);
  const entries: Array<{ path: string; text: string }> = [];
  hook!(null, entries);
  return entries[0].text;
}

/** Evaluate the generated `export const EXTPAY_CONFIG = {...} as const;` and return the object. */
function parse(text: string): ExtPayConfig {
  const m = text.match(/export const EXTPAY_CONFIG = ([\s\S]*) as const;\s*$/);
  expect(m, 'generated file has the expected shape').not.toBeNull();
  return JSON.parse(m![1]);
}

describe('generated extpay-config.ts (read by helpers at runtime)', () => {
  it('round-trips every option exactly', async () => {
    const cfg = parse(await generate({ extensionId: 'abc', priceDisplay: '$60', priceLabel: 'per year', trialDays: 14 }));
    expect(cfg).toEqual({ extensionId: 'abc', priceDisplay: '$60', priceLabel: 'per year', trialDays: 14 });
  });

  it('keeps trialDays: 0 (no trial) instead of replacing it with the default', async () => {
    expect(parse(await generate({ extensionId: 'abc', trialDays: 0 })).trialDays).toBe(0);
  });

  it('keeps an explicitly empty priceLabel instead of the "one-time" default', async () => {
    expect(parse(await generate({ extensionId: 'abc', priceLabel: '' })).priceLabel).toBe('');
  });

  it('escapes quotes, backslashes and newlines so the generated TypeScript stays valid', async () => {
    const tricky = 'a"b\\c\n`${x}`</script>';
    const text = await generate({ extensionId: 'abc', priceDisplay: tricky });
    expect(parse(text).priceDisplay).toBe(tricky);
    // Nothing leaks out of the string literal onto its own line.
    expect(text.split('\n').filter((l) => l.includes('</script>'))).toHaveLength(1);
  });

  it('marks the file as generated', async () => {
    expect(await generate({ extensionId: 'abc' })).toMatch(/^\/\/ Auto-generated by @brightbar-dev\/wxt-extpay/);
  });
});
