/**
 * @brightbar-dev/wxt-extpay — WXT module for ExtensionPay integration
 *
 * Handles:
 * - Injecting the extensionpay.com content script (required for payment detection)
 * - Providing typed config via wxt.config.ts
 *
 * Usage in wxt.config.ts:
 *   import extpayModule from '@brightbar-dev/wxt-extpay';
 *   export default defineConfig({
 *     modules: [extpayModule],
 *     extpay: { extensionId: 'my-extension' },
 *   });
 *
 * Usage in popup/options (import helpers directly):
 *   import { createExtPay } from '@brightbar-dev/wxt-extpay/helpers';
 *   const extpay = createExtPay();
 *   const user = await extpay.getUser();
 */

import { defineWxtModule, addEntrypoint } from 'wxt/modules';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Resolve to package root (works from both src/ and dist/)
const pkgRoot = __dirname.endsWith('/dist') || __dirname.endsWith('\\dist')
  ? path.resolve(__dirname, '..')
  : path.resolve(__dirname, '..');

export interface ExtPayModuleOptions {
  /** ExtensionPay extension ID (registered at extensionpay.com) */
  extensionId: string;
  /** Display price string shown in upsell UI (e.g. "$60") */
  priceDisplay?: string;
  /** Price label (e.g. "one-time", "per year") */
  priceLabel?: string;
  /** Trial duration in days (0 = no trial) */
  trialDays?: number;
}

export default defineWxtModule<ExtPayModuleOptions>({
  name: '@brightbar-dev/wxt-extpay',
  configKey: 'extpay',

  async setup(wxt, options) {
    if (!options?.extensionId) {
      throw new Error(
        '@brightbar-dev/wxt-extpay: extensionId is required. Set it in wxt.config.ts under "extpay".'
      );
    }

    // Inject the ExtPay content script for extensionpay.com
    // This is required for ExtPay to detect payment completion in real-time
    const contentScriptPath = path.resolve(pkgRoot, 'src', 'extpay-content.ts');

    addEntrypoint(wxt, {
      type: 'content-script',
      name: 'extpay',
      inputPath: contentScriptPath,
      outputDir: path.resolve(wxt.config.outDir, 'content-scripts'),
      options: {
        matches: ['https://extensionpay.com/*'],
        runAt: 'document_start',
      },
    });

    // Generate a config file that helpers can import at runtime
    const configPath = path.resolve(wxt.config.wxtDir, 'extpay-config.ts');

    wxt.hooks.hook('prepare:types', (_, entries) => {
      entries.push({
        path: configPath,
        text: `// Auto-generated by @brightbar-dev/wxt-extpay — do not edit
export const EXTPAY_CONFIG = ${JSON.stringify({
          extensionId: options.extensionId,
          priceDisplay: options.priceDisplay ?? '',
          priceLabel: options.priceLabel ?? 'one-time',
          trialDays: options.trialDays ?? 7,
        }, null, 2)} as const;
`,
      });
    });
  },
});
